
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar"; 
import Footer from "@/components/Footer/Footer";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-inter', 
});

export const metadata = {
  title: "Amicloud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased `}
      >
        <Navbar /> 
        <main>{children}</main> 
        <Footer /> 
      </body>
    </html>
  );
}
